/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--eh-canvas) / <alpha-value>)',
        ink: 'rgb(var(--eh-ink) / <alpha-value>)',
        body: 'rgb(var(--eh-body) / <alpha-value>)',
        muted: {
          DEFAULT: 'rgb(var(--eh-muted) / <alpha-value>)',
          soft: 'rgb(var(--eh-muted-soft) / <alpha-value>)',
        },
        hairline: {
          DEFAULT: 'var(--eh-hairline)',
          soft: 'var(--eh-hairline-soft)',
        },
        surface: {
          soft: 'rgb(var(--eh-surface-soft) / <alpha-value>)',
          card: 'rgb(var(--eh-surface-card) / <alpha-value>)',
          strong: 'rgb(var(--eh-surface-strong) / <alpha-value>)',
          dark: 'rgb(var(--eh-surface-dark) / <alpha-value>)',
          'dark-elevated': 'var(--eh-surface-dark-elevated-hex)',
        },
        brand: {
          accent: 'rgb(var(--eh-brand-accent) / <alpha-value>)',
          primary: 'rgb(var(--eh-brand-primary) / <alpha-value>)',
          'primary-active': 'var(--eh-brand-primary-active-hex)',
        },
        primary: {
          50: 'var(--eh-primary-50)',
          100: 'var(--eh-primary-100)',
          200: 'var(--eh-primary-200)',
          300: 'var(--eh-primary-300)',
          400: 'var(--eh-primary-400)',
          500: 'var(--eh-primary-500)',
          600: 'var(--eh-primary-600)',
          700: 'var(--eh-primary-700)',
          800: 'var(--eh-primary-800)',
          900: 'var(--eh-primary-900)',
          DEFAULT: 'rgb(var(--eh-primary) / <alpha-value>)',
          foreground: 'rgb(var(--eh-primary-fg) / <alpha-value>)',
        },
        success: 'var(--eh-success-hex)',
        warning: 'var(--eh-warning-hex)',
        error: 'var(--eh-error-hex)',
        on: {
          primary: 'var(--eh-on-primary-hex)',
          dark: 'var(--eh-ink-hex)',
          'dark-soft': 'var(--eh-muted-hex)',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'sans-serif',
        ],
        display: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'sans-serif',
        ],
        mono: ['"Roboto Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-sm': ['28px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
        'title-lg': ['22px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '500' }],
        'title-md': ['18px', { lineHeight: '1.4', fontWeight: '500' }],
        'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      width: {
        popup: '800px',
      },
      height: {
        popup: '600px',
        'popup-header': '56px',
        'popup-content': '480px',
        'popup-footer': 'var(--popup-footer-h)',
      },
      borderRadius: {
        'eh-xs': '4px',
        'eh-sm': '8px',
        'eh-md': '16px',
        'eh-lg': '22px',
        'eh-xl': '30px',
        'eh-cta': '32px',
        'eh-2xl': '22px',
        'eh-3xl': '30px',
      },
      boxShadow: {
        card: 'var(--eh-shadow-card)',
        'card-elevated': 'var(--eh-shadow-card-elevated)',
        pill: 'var(--eh-shadow-pill)',
        glow: 'var(--eh-glow)',
      },
    },
  },
  plugins: [],
};
