/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--eh-canvas) / <alpha-value>)',
        ink: 'rgb(var(--eh-ink) / <alpha-value>)',
        body: 'rgb(var(--eh-body) / <alpha-value>)',
        muted: {
          DEFAULT: 'rgb(var(--eh-muted) / <alpha-value>)',
          soft: 'rgb(var(--eh-muted-soft) / <alpha-value>)',
        },
        hairline: {
          DEFAULT: 'var(--eh-hairline)',
          soft: 'var(--eh-hairline-soft)',
        },
        surface: {
          soft: 'rgb(var(--eh-surface-soft) / <alpha-value>)',
          card: 'rgb(var(--eh-surface-card) / <alpha-value>)',
          strong: 'rgb(var(--eh-surface-strong) / <alpha-value>)',
          dark: 'rgb(var(--eh-surface-dark) / <alpha-value>)',
          'dark-elevated': 'rgb(var(--eh-surface-dark-elevated) / <alpha-value>)',
        },
        brand: {
          accent: 'rgb(var(--eh-brand-accent) / <alpha-value>)',
          primary: 'rgb(var(--eh-brand-primary) / <alpha-value>)',
          'primary-active': 'rgb(var(--eh-brand-primary-active) / <alpha-value>)',
        },
        primary: {
          50: 'rgb(var(--eh-primary-50) / <alpha-value>)',
          100: 'rgb(var(--eh-primary-100) / <alpha-value>)',
          200: 'rgb(var(--eh-primary-200) / <alpha-value>)',
          300: 'rgb(var(--eh-primary-300) / <alpha-value>)',
          400: 'rgb(var(--eh-primary-400) / <alpha-value>)',
          500: 'rgb(var(--eh-primary-500) / <alpha-value>)',
          600: 'rgb(var(--eh-primary-600) / <alpha-value>)',
          700: 'rgb(var(--eh-primary-700) / <alpha-value>)',
          800: 'rgb(var(--eh-primary-800) / <alpha-value>)',
          900: 'rgb(var(--eh-primary-900) / <alpha-value>)',
          DEFAULT: 'rgb(var(--eh-primary) / <alpha-value>)',
          foreground: 'rgb(var(--eh-primary-fg) / <alpha-value>)',
        },
        success: 'rgb(var(--eh-success) / <alpha-value>)',
        warning: 'rgb(var(--eh-warning) / <alpha-value>)',
        error: 'rgb(var(--eh-error) / <alpha-value>)',
        on: {
          primary: 'rgb(var(--eh-on-primary) / <alpha-value>)',
          dark: 'rgb(var(--eh-ink) / <alpha-value>)',
          'dark-soft': 'rgb(var(--eh-muted) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: [
          '"Roboto Mono"',
          'Inter',
          '"Noto Sans SC"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          '"PingFang SC"',
          '"Microsoft YaHei"',
          '"Noto Sans CJK SC"',
          '"Source Han Sans SC"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        display: [
          '"Roboto Mono"',
          'Inter',
          '"Noto Sans SC"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          '"PingFang SC"',
          '"Microsoft YaHei"',
          '"Noto Sans CJK SC"',
          '"Source Han Sans SC"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        mono: ['"Roboto Mono"', 'Inter', '"Noto Sans SC"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-sm': ['28px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
        'title-lg': ['22px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '500' }],
        'title-md': ['18px', { lineHeight: '1.4', fontWeight: '500' }],
        'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      width: {
        popup: '800px',
      },
      height: {
        popup: '600px',
        'popup-header': '56px',
        'popup-content': '480px',
        'popup-footer': 'var(--popup-footer-h)',
      },
      borderRadius: {
        'eh-xs': '4px',
        'eh-sm': '8px',
        'eh-md': '16px',
        'eh-lg': '22px',
        'eh-xl': '30px',
        'eh-cta': '32px',
        'eh-2xl': '22px',
        'eh-3xl': '30px',
      },
      boxShadow: {
        card: 'var(--eh-shadow-card)',
        'card-elevated': 'var(--eh-shadow-card-elevated)',
        pill: 'var(--eh-shadow-pill)',
        glow: 'var(--eh-glow)',
      },
    },
  },
  plugins: [],
};
