name: Build And Upload Extension Zip Via Artifact

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/bun.lockb') }}
          
      - run: bun install
      - run: bun run build

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
